<?php

namespace Database\Seeders;

use App\Models\CrewCandidate;
use Illuminate\Database\Seeder;

/**
 * Five candidates covering the shapes the pool has to handle: deck and engine ranks,
 * a referral, an agency hire with a cost, a fresh school leaver and a blacklisted one.
 */
class CrewCandidateSeeder extends Seeder
{
    public function run(): void
    {
        $candidates = [
            [
                'full_name' => 'Bagus Prasetyo',
                'gender' => 'male',
                'date_of_birth' => '1985-04-12',
                'place_of_birth' => 'Semarang',
                'marital_status' => 'married',
                'religion' => 'Islam',
                'blood_type' => 'O',
                'nik' => '3374011204850001',
                'passport_no' => 'C1234567',
                'passport_expiry' => '2028-03-01',
                'passport_issue_place' => 'Semarang',
                'seaman_book_no' => 'SB-100201',
                'seaman_book_expiry' => '2027-06-30',
                'seaman_book_issue_place' => 'Semarang',
                'phone' => '081234500001',
                'whatsapp' => '081234500001',
                'email' => 'bagus.prasetyo@example.com',
                'address' => 'Jl. Pemuda No. 12',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50132',
                'emergency_contact_name' => 'Rina Prasetyo',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '081234500002',
                'applied_rank' => 'Master',
                'preferred_vessel_type' => 'Tanker',
                'years_of_experience' => 18,
                'last_vessel_name' => 'MT Bintang Samudera',
                'last_rank' => 'Chief Officer',
                'last_sign_off_date' => '2026-05-20',
                'coc_type' => 'ANT-I',
                'coc_number' => 'COC-ANT1-8891',
                'coc_expiry' => '2029-01-15',
                'cop_certificates' => [
                    ['name' => 'Basic Safety Training', 'number' => 'BST-2201', 'expiry' => '2027-02-01'],
                    ['name' => 'Advanced Fire Fighting', 'number' => 'AFF-3310', 'expiry' => '2027-08-11'],
                ],
                'mcu_expiry' => '2026-11-30',
                'endc_expiry' => '2027-01-20',
                'source' => 'walk_in',
                'status' => 'applicant',
                'availability_date' => '2026-08-01',
                'expected_salary' => 45000000,
            ],
            [
                'full_name' => 'Hendra Setiawan',
                'gender' => 'male',
                'date_of_birth' => '1990-09-03',
                'place_of_birth' => 'Surabaya',
                'marital_status' => 'married',
                'nik' => '3578010309900002',
                'seaman_book_no' => 'SB-100202',
                'seaman_book_expiry' => '2028-02-28',
                'phone' => '081234500003',
                'email' => 'hendra.setiawan@example.com',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'applied_rank' => 'Chief Engineer',
                'preferred_vessel_type' => 'Bulk Carrier',
                'years_of_experience' => 12,
                'last_vessel_name' => 'MV Nusantara Jaya',
                'last_rank' => 'Second Engineer',
                'last_sign_off_date' => '2026-06-10',
                'coc_type' => 'ATT-I',
                'coc_number' => 'COC-ATT1-4412',
                'coc_expiry' => '2028-07-01',
                'mcu_expiry' => '2026-08-15',
                'source' => 'referral',
                'referred_by_employee_id' => 'HR-EMP-00001',
                'status' => 'in_process',
                'availability_date' => '2026-07-25',
                'expected_salary' => 52000000,
            ],
            [
                'full_name' => 'Yusuf Ramadhan',
                'gender' => 'male',
                'date_of_birth' => '1996-12-19',
                'place_of_birth' => 'Makassar',
                'marital_status' => 'single',
                'nik' => '7371011912960003',
                'seaman_book_no' => 'SB-100203',
                'phone' => '081234500004',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'applied_rank' => 'Third Officer',
                'years_of_experience' => 4,
                'coc_type' => 'ANT-III',
                'coc_number' => 'COC-ANT3-7781',
                'coc_expiry' => '2027-05-05',
                'mcu_expiry' => '2026-07-29', // expiring within the month
                'source' => 'agency',
                'source_agency_id' => 'PT Bahari Manning',
                'source_cost' => 7500000,
                'status' => 'applicant',
                'availability_date' => '2026-07-23',
                'expected_salary' => 22000000,
            ],
            [
                'full_name' => 'Dewi Anggraini',
                'gender' => 'female',
                'date_of_birth' => '2002-02-08',
                'place_of_birth' => 'Cilacap',
                'marital_status' => 'single',
                'nik' => '3301024802020004',
                'phone' => '081234500005',
                'email' => 'dewi.anggraini@example.com',
                'city' => 'Cilacap',
                'province' => 'Jawa Tengah',
                'applied_rank' => 'Deck Cadet',
                'years_of_experience' => 0,
                'coc_type' => 'Rating',
                'source' => 'school',
                'source_school' => 'Politeknik Ilmu Pelayaran Semarang',
                'status' => 'applicant',
                'availability_date' => '2026-09-01',
                'expected_salary' => 6000000,
                'notes' => 'Fresh graduate, sea project selesai Juli 2026.',
            ],
            [
                'full_name' => 'Rudi Hartono',
                'gender' => 'male',
                'date_of_birth' => '1979-07-30',
                'place_of_birth' => 'Batam',
                'marital_status' => 'divorced',
                'nik' => '2171013007790005',
                'seaman_book_no' => 'SB-100205',
                'seaman_book_expiry' => '2025-12-31', // already expired
                'phone' => '081234500006',
                'city' => 'Batam',
                'province' => 'Kepulauan Riau',
                'applied_rank' => 'Bosun',
                'years_of_experience' => 22,
                'last_vessel_name' => 'AHTS Sinar Laut',
                'last_rank' => 'Bosun',
                'last_sign_off_date' => '2025-11-02',
                'coc_type' => 'Rating',
                'mcu_expiry' => '2025-10-01',
                'source' => 'head_hunter',
                'source_cost' => 12000000,
                'status' => 'blacklist',
                'notes' => 'Tidak lapor sign on dua kali berturut-turut.',
            ],
        ];

        foreach ($candidates as $candidate) {
            CrewCandidate::updateOrCreate(
                ['nik' => $candidate['nik']],
                $candidate + ['created_by' => 'seeder', 'updated_by' => 'seeder'],
            );
        }
    }
}
